### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by q351941406** [fedden/pluribus-poker-AI#33]
How does it work?

**Comment by big-c-note** [comment]
- You can check out a code example in the [README](https://github.com/fedden/pluribus-poker-AI/blob/develop/README.md)
- You can see the progress that has been made on the algorithms in the [research folder](https://github.com/fedden/pluribus-poker-AI/tree/develop/research)
- You can read about the algorithms and design specs [here](https://github.com/fedden/pluribus-poker-AI/tree/develop/paper)

**Comment by fedden** [comment]
Gonna close this as the codebase is still very alpha and the answer to this question will change over the coming months, please keep an eye on the README and the develop branch, thanks for your interest!
