### ISSUE TITLE
webpack.dev.conf.js is missing in vue project

### ISSUE THREAD

**Issue by Mikeyjou** [fedden/pluribus-poker-AI#45]
I can't run the frontend because build folder is missing.

**Comment by fedden** [comment]
Okay I'd warn that this is very alpha and at this stage it's not very helpful; the front end just visualises a freshly initialised `ShortDeckPokerState` object.

If you are aware of that already, can you share what the commands you ran to build the frontend, and where you ran the commands?

**Comment by Mikeyjou** [comment]
I run the command "npm run dev" in "frontend" folder but it pops up the following error message.

PS F:\poker\pluribus-poker-AI\applications\visualisation\frontend> npm run dev

> poker_ai_visualisation@1.0.0 dev F:\poker\pluribus-poker-AI\applications\visualisation\frontend
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'F:\poker\pluribus-poker-AI\applications\visualisation\frontend\build\webpack.dev.conf.js'
Require stack:
- F:\poker\pluribus-poker-AI\applications\visualisation\frontend\node_modules\webpack-cli\bin\utils\convert-argv.js
- F:\poker\pluribus-poker-AI\applications\visualisation\frontend\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at WEBPACK_OPTIONS (F:\poker\pluribus-poker-AI\applications\visualisation\frontend\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (F:\poker\pluribus-poker-AI\applications\visualisation\frontend\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at F:\poker\pluribus-poker-AI\applications\visualisation\frontend\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (F:\poker\pluribus-poker-AI\applications\visualisation\frontend\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at Object.<anonymous> (F:\poker\pluribus-poker-AI\applications\visualisation\frontend\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\poker\\pluribus-poker-AI\\applications\\visualisation\\frontend\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'F:\\poker\\pluribus-poker-AI\\applications\\visualisation\\frontend\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poker_ai_visualisation@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poker_ai_visualisation@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MikeyJou\AppData\Roaming\npm-cache\_logs\2020-04-06T16_22_00_294Z-debug.log


Should I write webpack.dev.conf.js by myself?

**Comment by Mikeyjou** [comment]
I can run frontend after initializing the webpack by myself.

**Comment by fedden** [comment]
Hey so sorry I'm not a web dev. I've pushed what I have already to `build/` to the develop branch

**Comment by fedden** [comment]
I can see you've done some nice front end work in another PR though so would like to check that out soon!
