### ISSUE TITLE
Check the number of bet chips in the pot for the preflop first player 

### ISSUE THREAD

**Issue by fedden** [fedden/pluribus-poker-AI#58]
**Describe the bug**
Where we change the player order pre-flop: https://github.com/fedden/pluribus-poker-AI/blob/8534754c776b1e3e44a0727c625f3d88e528e223/pluribus/games/short_deck/state.py#L84

What is in the pot for the players `player_i_order[2:]` to check/bet against?

I think as it stands the logic is 0 chips, which is of course wrong - we need to add the small/big blinds to the pot.

**Comment by big-c-note** [comment]
I did not notice this while debugging. I don’t think it’s an issue if I understand you correctly. I think player 0 was small blind and player 1 was big blind. Of course do your due diligence.

**Comment by fedden** [comment]
If player 2 then checks, what do they check - is it 0 chips?

**Comment by big-c-note** [comment]
Oh ok, I misread the issue. I do not recall off the top of my head. I don’t think I reviewed that particular action. Of course, expected behavior would be `state.legal_actions = [‘fold’, ‘call’, ‘raise’]` with `‘call’` needing to place in 100 chips for the player.

**Comment by fedden** [comment]
yeah I'm pretty sure it'll be wrong, but will double check this tonight and add tests to check
