### ISSUE TITLE
May I ask...how to solve this please?

### ISSUE THREAD

**Issue by jiahui-x** [fedden/pluribus-poker-AI#60]
![1586512716(1)](https://user-images.githubusercontent.com/57308120/78982814-8c081d00-7b55-11ea-8b1b-be93e1e1c969.jpg)

**Comment by fedden** [comment]
Hey @jiahui-x apologies for this I think I broke something with an github automatic patch a little while back. There are some open PRs that will probably fix this and I want to dockerise this anyway so watch this space, I'll get back to you

**Comment by jiahui-x** [comment]
ok , thanks(^_^)

**Comment by fedden** [comment]
Hey @jiahui-x I've commited to develop, can you try again with the latest develop?

**Comment by jiahui-x** [comment]
I've tried successfully, thank u!
